logging:
  level:
    org.springframework.web: debug
  file:
    path: logs
spring:
  application:
    name: vorovayka
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  web:
    resources:
      add-mappings: false
server:
  error:
    whitelabel:
      enabled: false
  forward-headers-strategy: native
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
  api-docs:
    path: /docs/v3/api-docs
app:
  logic:
    orders:
      expiration-time: 30
      expiration-time-unit: MINUTES
  docs:
    version: ${API_VERSION}
  security:
    cors:
      allowed-headers: '*'
      allowed-origins: ${CORS_ORIGINS:'*'}
      allowed-methods: ${CORS_METHODS:'GET,POST,PUT,DELETE,PATCH,OPTIONS,HEAD'}
      allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
      max-age: ${CORS_MAX_AGE:60}
    auth:
      access-token:
        private-key-file: "secret.pem"
        expires-in: 600000
        authorities-claim: "roles"
        cookie:
          key: "access_token"
          path: "/"
      refresh-token:
        expires-in: 2592000000
        cookie:
          key: "refresh_token"
          path: "/auth"
  paths:
    static-files: static
    log-files: logs
  media:
    base-path: media
    images:
      format: png
      base-path: original
      min-width: 512
      min-height: 512
    thumbnails:
      format: png
      base-path: thumbnails
      width: 150
      height: 150
