spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:vorovayka
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
server:
  forward-headers-strategy: none
keycloak:
  enabled: false
app:
  docs:
    version: v0
