name: Maven + Docker CI/CD

on:
  push:
    branches: [ "master", "dev" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean package -DskipTests=true --file pom.xml

    - name: Push Docker image
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        DOCKER_REGISTRY_USER: ${{ secrets.REGISTRY_LOGIN }}
        DOCKER_REGISTRY_PASS: ${{ secrets.REGISTRY_PASS }}
        DOCKER_REGISTRY_HOST: ${{ vars.REGISTRY_HOST }}
      run: mvn docker:build docker:push --file pom.xml
